repos:
-   repo: https://github.com/Lucas-C/pre-commit-hooks-nodejs
    rev: ''
    hooks:
    -   id: dockerfile_lint

-   repo: https://github.com/IamTheFij/docker-pre-commit
    rev: ''
    hooks:
    -   id: docker-compose-check

-   repo: https://github.com/pryorda/dockerfilelint-precommit-hooks
    rev: ''
    hooks:
    -   id: dockerfilelint



