name: Build and push docker images

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
  push:
    branches:
      - 'master'
  pull_request:
    types: [opened]

jobs:
  docker-images:
    strategy:
      matrix:
        repo: [cpp, noetic, humble, latex]
        target: [base, dev]
        include:
          - repo: noetic
            target: opencv
          - repo: humble
            target: opencv
          - repo: cpp
            target: opencv
          - repo: noetic
            target: full
          - repo: noetic
            target: gazebo
          - repo: noetic
            target: gazebo-nvidia
          - repo: humble
            target: full
          - repo: humble
            target: gazebo
          - repo: humble
            target: gazebo-nvidia
          - repo: latex
            target: full
        
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout code
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./${{ matrix.repo }}.Dockerfile
          target: ${{ matrix.target }}
          tags:  ${{ secrets.DOCKERHUB_USERNAME }}/${{ matrix.repo }}:${{ matrix.target }}
          push: true
